#!/bin/sh

# Optional switch -n N: number of times to submit
# Can also have -q Queue

if [ "$1" = "-n" ]
  then N=$2
       shift 2
  else N=1
fi

if [ "$1" = "-q" ]
  then Q="-q $2"
       shift 2
  else Q=''
fi

while true
  do
  bsub -o tmp.bout -e tmp.berr $Q "$*"
  N=$((N-1))
  if [ $N = 0 ]
    then break
  fi
  sleep 2
  done

