#!/bin/bash
#
# This bamcheck wrapper omits three troublesome high-coverage regions
#   on chr2 and chr9 from duplicate reads calculation. It does
#   so by running bamcheck twice and replacing the field 'SN  reads duplicated:' 
#
# After excluding, the regions are:
#       1   1   197195432
#       10  1   129993255
#       11  1   121843856
#       12  1   121257530
#       13  1   120284312
#       14  1   125194864
#       15  1   103494974
#       16  1   98319150
#       17  1   95272651
#       18  1   90772031
#       19  1   61342430
#       2   1   98501004
#       2   98508030    181748087
#       3   1   159599783
#       4   1   155630120
#       5   1   152537259
#       6   1   149517037
#       7   1   152524553
#       8   1   131738871
#       9   3039044 35111653
#       9   35113661    124076172
#       MT  1   16299
#       X   1   166650296
#       Y   1   15902555
#


TMPFILE=`mktemp /tmp/bamcheck-mousewrapper.XXXXXXXXXX` || exit 1

die()
{
    cat $TMPFILE
    rm -f $TMPFILE
    exit 1
}

trap 'die' TERM
trap 'die' INT

if [ ! -t 0 ]; then
    echo "The mousewrapper does not accept streamed BAMs."
    die
fi

bamcheck $@ -t /lustre/scratch102/projects/mouse/ref/bamcheck-mousewrapper.regions > $TMPFILE || die
DUPL=`cat $TMPFILE | grep ^SN | grep 'reads duplicated:'` || die
rm -f $TMPFILE

bamcheck $@ | sed "s,^SN\treads duplicated:.*,$DUPL," || die

exit 0


