#! /bin/sh
# Git proxy wrapper, per http://scratchy.internal.sanger.ac.uk/wiki/index.php/Using_Git
# Called by git with <hostname> <port>

exec socat - "PROXY:wwwcache.sanger.ac.uk:$1:$2,proxyport=3128"
# ,proxyauth=user:pass

