#!/bin/bash

# "Clean" the specified directories of all files created by "map maq"
# or "maq rmdup" or "maq merge", i.e. by "g1k.pl map" or "g1k.pl rmd"
# or "g1k.pl mrg".  These will typically be lane* or lane*/sample
# directories, or higher-level ones (lib or individual).

for d in $*
  do
  if [ -d $d ]
    then
      pushd $d
      rm -rf map unmap* read? *.err *.sh *.out aln* cmd* *@*bfq
      popd
    else 
      echo $d not found
  fi
  done
