#!/usr/bin/env perl

use strict;
use warnings;
use Getopt::Long;
use Carp;

my ($package, $help);
my $shell = $ENV{SHELL};

GetOptions(
    'p|package=s'    =>  \$package,
    'h|help'	     =>  \$help,
);

($package && !$help) or die <<USAGE;
    Usage: $0 -p package_name
    
    This will install a python package to the vertres python library specified below.
    
    To use:
    Simply use the -p flag and the package name to use easy_install on uk10k and precise-dev64.
    Note: this will install the latest version by default, but you can specify a particular version like this-
      -p package_name==1.2.3
    
USAGE

my $pythonpath = '/software/vertres/lib/python/python-2.7.3/lib/python2.7/site-packages';
my $lib_directory = '/software/vertres/lib/python/python-2.7.3';
#csh/tcsh or POSIX-compliant shells (bash, ksh, dash...) need slightly different pythonpath set up
my $ppath_setup = ( $shell =~ /tcsh/ || $shell =~ /csh/ ) ? "setenv PYTHONPATH $pythonpath;" : "PYTHONPATH=$pythonpath";

foreach my $server ('uk10k-login', 'precise-dev64') {
    warn "\nInstalling $package on $server\n";
    system(qq[ssh -A $server "umask 002; cd $lib_directory/bin; $ppath_setup ./easy_install --prefix=$lib_directory -U $package"]);
}

exit;
