ALTER TABLE assembly MODIFY COLUMN name VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE assembly MODIFY COLUMN reference_size bigint(20) DEFAULT NULL;
ALTER TABLE exome_design MODIFY COLUMN name VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE file MODIFY COLUMN file_id mediumint(8) unsigned NOT NULL DEFAULT '0';
ALTER TABLE file MODIFY COLUMN name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE image MODIFY COLUMN mapstats_id mediumint(8) unsigned NOT NULL DEFAULT '0';
ALTER TABLE image MODIFY COLUMN name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE individual MODIFY COLUMN name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE individual MODIFY COLUMN hierarchy_name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE individual MODIFY COLUMN alias varchar(40) NOT NULL DEFAULT '';
ALTER TABLE lane  MODIFY COLUMN seq_request_id mediumint(8) unsigned NOT NULL DEFAULT '0';
ALTER TABLE lane  MODIFY COLUMN npg_qc_status enum('pending','pass','fail','-') DEFAULT 'pending';
ALTER TABLE lane  MODIFY COLUMN auto_qc_status enum('no_qc','passed','failed') DEFAULT 'no_qc';
ALTER TABLE lane  MODIFY COLUMN qc_status enum('no_qc','pending','passed','failed','gt_pending','investigate') DEFAULT 'no_qc';
ALTER TABLE library  MODIFY COLUMN library_request_id mediumint(8) unsigned NOT NULL DEFAULT '0';
ALTER TABLE library  MODIFY COLUMN name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE library  MODIFY COLUMN auto_qc_status enum('no_qc','passed','failed') DEFAULT 'no_qc';
ALTER TABLE library_multiplex_pool MODIFY COLUMN multiplex_pool_id smallint(5) unsigned NOT NULL DEFAULT '0';
ALTER TABLE library_request MODIFY COLUMN library_request_id mediumint(8) unsigned NOT NULL DEFAULT '0';
ALTER TABLE library_type MODIFY COLUMN name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE mapper MODIFY COLUMN name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE mapper MODIFY COLUMN version varchar(40) NOT NULL DEFAULT '0';
ALTER TABLE mapstats MODIFY COLUMN mapstats_id mediumint(8) unsigned NOT NULL DEFAULT '0';
ALTER TABLE multiplex_pool MODIFY COLUMN name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE population MODIFY COLUMN name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE project MODIFY COLUMN project_id smallint(5) unsigned NOT NULL DEFAULT '0';
ALTER TABLE sample MODIFY COLUMN project_id smallint(5) unsigned NOT NULL DEFAULT '0';
ALTER TABLE sample MODIFY COLUMN name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE seq_centre MODIFY COLUMN name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE seq_request MODIFY COLUMN seq_request_id mediumint(8) unsigned NOT NULL DEFAULT '0';
ALTER TABLE seq_request MODIFY COLUMN seq_type enum('HiSeq Paired end sequencing','Illumina-A HiSeq Paired end sequencing','Illumina-A Paired end sequencing','Illumina-A Pulldown ISC','Illumina-A Pulldown SC','Illumina-A Pulldown WGS','Illumina-A Single ended hi seq sequencing','Illumina-A Single ended sequencing','Illumina-B HiSeq Paired end sequencing','Illumina-B Paired end sequencing','Illumina-B Single ended hi seq sequencing','Illumina-B Single ended sequencing','Illumina-C HiSeq Paired end sequencing','Illumina-C MiSeq sequencing','Illumina-C Paired end sequencing','Illumina-C Single ended hi seq sequencing','Illumina-C Single ended sequencing','MiSeq sequencing','Paired end sequencing','Single ended hi seq sequencing','Single Ended Hi Seq Sequencing Control','Single ended sequencing') DEFAULT 'Single ended sequencing';
ALTER TABLE seq_tech MODIFY COLUMN name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE species MODIFY COLUMN name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE submission MODIFY date DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE submission MODIFY COLUMN name varchar(255) NOT NULL DEFAULT '';
ALTER TABLE library_multiplex_pool MODIFY COLUMN library_id int(10) unsigned NOT NULL DEFAULT '0';
ALTER TABLE library MODIFY COLUMN library_id int(10) unsigned NOT NULL DEFAULT '0';
